spring:
  profiles:
    active: dev
#正式服 active: official
#测试服 active: test
#开发 active: dev
auto:
  swagger2:
    apiInfo:
      version: 1.0.0
      title: 大格大药房线上商城管理平台
      description: 大格大药房线上商城接口文档
