spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    #password:
    timeout: 0
    pool:
      max-active: 200
      max-wait: 10000
      max-idle: 150
      min-idle: 50
    lock:
      waitTimeOut: 5
      lockTimeOut: 30
  session:
    store-type: none
  activemq:
    broker-url: tcp://127.0.0.1:61616
    user: admin
    password: admin
    pool:
      enabled: false #如果此处设置为true，需要加如下的依赖包，否则会自动配置失败，报JmsMessagingTemplate注入失败
      #<dependency>
      #         <groupId>org.apache.activemq</groupId>
      #            <artifactId>activemq-pool</artifactId>
      #        <!-- <version>5.7.0</version> -->
      #    </dependency>
datasource:
  type: com.alibaba.druid.pool.DruidDataSource
  master:
#   url: jdbc:mysql://47.104.179.143:3306/wmdb_v2?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&tinyInt1isBit=false
    url: jdbc:mysql://192.168.3.239:3306/wmdb_v2?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&tinyInt1isBit=false&sslMode=DISABLED&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
#    username: dage
#    password: dgdyf2021,./]]
#    url: jdbc:mysql://127.0.0.1:3306/qztdb?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&tinyInt1isBit=false
    username: dev_admin
    password: dev_admin

    driverClassName: com.mysql.cj.jdbc.Driver
    initialSize: 5
    maxActive: 20
    minIdle: 5
    maxWait: 60000
    defaultReadOnly: false
    filters: stat
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=2000
    useGlobalDataSourceStat: true
  slaver:
#    url: jdbc:mysql://47.104.179.143:3306/wmdb_v2?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&tinyInt1isBit=false
#    url: jdbc:mysql://127.0.0.1:3306/wmdb_v2?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&tinyInt1isBit=false
#    username: dage
#    password: dgdyf2021,./]]
    url: jdbc:mysql://192.168.3.239:3306/qztdb?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&tinyInt1isBit=false&sslMode=DISABLED&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: dev_admin
    password: dev_admin

    driverClassName: com.mysql.cj.jdbc.Driver
    initialSize: 5
    maxActive: 20
    minIdle: 5
    maxWait: 60000
    defaultReadOnly: false
    filters: stat
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=2000
    useGlobalDataSourceStat: true


mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  #typeAliasesPackage: com.baomidou.springboot.entity
  #typeEnumsPackage: com.baomidou.springboot.entity.enums
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 2
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置
    #key-generator: com.baomidou.springboot.xxx
    #逻辑删除配置
    #logic-delete-value: 0
    #logic-not-delete-value: 1
    #sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    #自定义填充策略接口实现
    #meta-object-handler: com.baomidou.springboot.xxx
    #自定义SQL注入器
    #sql-injector: com.baomidou.springboot.xxx
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true

server:
  port: 30035

dubbo:
  application:
    name: jww-ump-dubbo-provider
    owner: jww-ump-dubbo-provider
  registry:
    protocol: zookeeper
    address: 127.0.0.1:2181

  protocol:
    name: dubbo
    port: 20880

logging:
  level:
    root: info
sms:
  appid: 1400057682
  appkey: 5df31e529354c82e8aa2c4dfc214998f
  testPhone: 17790072993
  testFlage: 1
#testFlage = 0 代表给页面传入的手机号发短信 1代表发送指定人